env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2022
  sourceType: module
rules:
  - import/no-extraneous-dependencies: off
  - import/no-unresolved: off
  - no-console: off
  - no-await-in-loop: off
  - no-restricted-syntax: off



