---
Resources:
  StepFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: ${self:custom.logRetentionInDays}
      LogGroupName: /aws/vendedlogs/states/stepFunctions${self:custom.titledStage}

  StepFunctionExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogsDeliveryFullAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:DescribeLogGroups
                  - logs:DescribeResourcePolicies
                  - logs:GetLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:UpdateLogDelivery
                Resource:
                  - "*"
        - PolicyName: XRayAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                  - xray:PutTelemetryRecords
                  - xray:PutTraceSegments
                Resource:
                  - "*"
        - PolicyName: StepFunctionAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                  - states:DescribeExecution
                  - states:StopExecution
                Resource:
                  - arn:aws:states:${aws:region}:${aws:accountId}:stateMachine:*${self:custom.titledStage}
        - PolicyName: LambdaAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:service}-${self:custom.stage}-*
        - PolicyName: AppConfigAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - appconfig:GetLatestConfiguration
                  - appconfig:StartConfigurationSession
                Resource:
                  - arn:aws:appconfig:${aws:region}:${aws:accountId}:application/*
        - PolicyName: EventBridgeAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource:
                  - arn:aws:events:${aws:region}:${aws:accountId}:event-bus/default
        - PolicyName: DynamoDbAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGet*
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeStream
                  - dynamodb:Get*
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWrite*
                  - dynamodb:CreateTable
                  - dynamodb:Delete*
                  - dynamodb:Update*
                  - dynamodb:PutItem
                Resource:
                  - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Retour${self:custom.titledStage}
        - PolicyName: ChildStepFunctionExecutionPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - events:PutTargets
                  - events:PutRule
                  - events:DescribeRule
                Resource:
                  - !Sub arn:aws:events:${aws:region}:${aws:accountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule
